[2021-04-24 11:39:50,982] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,433] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,434] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,434] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:39:51,434] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,834] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-08-01T00:00:00+00:00
[2021-04-24 11:39:52,031] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-08-01T00:00:00+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp1kbi15y9', '--error-file', '/tmp/tmphqvct80t']
[2021-04-24 11:39:52,032] {standard_task_runner.py:77} INFO - Job 29: Subtask Stage_songs
[2021-04-24 11:39:51,886] {standard_task_runner.py:52} INFO - Started process 111 to run task
[2021-04-24 11:39:53,094] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:39:54,602] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-01T00:00:00+00:00
[2021-04-24 11:39:54,608] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:39:54,860] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:39:54,906] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20190801T000000, start_date=20210424T113951, end_date=20210424T113954
[2021-04-24 11:39:55,813] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:15:55,056] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [queued]>
[2021-04-27 20:15:55,778] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [queued]>
[2021-04-27 20:15:55,790] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:15:55,802] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:15:55,812] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:15:56,414] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-08-01T00:00:00+00:00
[2021-04-27 20:15:57,087] {standard_task_runner.py:52} INFO - Started process 103 to run task
[2021-04-27 20:15:57,535] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-08-01T00:00:00+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp79fjf9fn', '--error-file', '/tmp/tmp4uh8nlqp']
[2021-04-27 20:15:57,622] {standard_task_runner.py:77} INFO - Job 26: Subtask Stage_songs
[2021-04-27 20:15:59,838] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:01,601] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-01T00:00:00+00:00
[2021-04-27 20:16:01,611] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:01,648] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:01,725] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20190801T000000, start_date=20210427T201555, end_date=20210427T201601
[2021-04-27 20:16:04,127] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:33:11,639] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:12,081] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:12,092] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:12,113] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:33:12,113] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:12,734] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-08-01T00:00:00+00:00
[2021-04-27 20:33:13,554] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-08-01T00:00:00+00:00', '--job-id', '25', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp7u2wu67i', '--error-file', '/tmp/tmp631wdufe']
[2021-04-27 20:33:13,372] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2021-04-27 20:33:13,661] {standard_task_runner.py:77} INFO - Job 25: Subtask Stage_songs
[2021-04-27 20:33:16,718] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-08-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:33:20,072] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-01T00:00:00+00:00
[2021-04-27 20:33:20,073] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:33:20,074] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:33:20,544] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:33:22,321] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:33:22,785] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:33:23,096] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:33:25,915] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:33:25,921] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20190801T000000, start_date=20210427T203311, end_date=20210427T203325
[2021-04-27 20:33:26,461] {local_task_job.py:146} INFO - Task exited with return code 1
